#pragma once
enum Greska
{
	NEMA_MESTA, //1
	MOZE_SE_SKLONITI_SAMO_ELEMENT_KOJI_JE_ZADNJI_UNESEN, //2
	GRESKA_SA_HLADNJACOM, //3
	ZAGLAVILA_SE_VRATA_HLADNJACE, //4
	NEMA_DOVOLJNO_MESTA_U_GAJBICI, //5


};