//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP.EF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_telefon
    {
        public long student_telefon_id { get; set; }
        public long student_id { get; set; }
        public string telefon { get; set; }
    
        public virtual student student { get; set; }
    }
}
